os:
  - linux

dist:
  - xenial

language:
  - node_js

node_js:
  - "stable"

cache:
  directories:
    - $HOME/server/node_modules
    - $HOME/client/node_modules

install:
  - npm install --prefix client
  - npm install --prefix server

script:
  - npm run eslint --prefix client && npm run eslint --prefix server && npm run test --prefix server && npm run devTest --prefix server
