os:
  - linux

dist:
  - xenial

language: node_js

node_js:
  - "stable"

cache:
  directories:
    - $HOME/node_modules
    - $HOME/client/node_modules

install:
  - npm install
  - cd client && npm install && cd ../

script:
  - npm run eslint && npm test && npm run devTest